# Modified from: https://documenter.juliadocs.org/stable/man/hosting/

name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'
      - name: Install dependencies, build, and deploy
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
            Pkg.add("Documenter")'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Needed due to https://github.com/JuliaDocs/Documenter.jl/issues/1177
          DOCUMENTER_KEY: ${{ secrets.ACCESS_TOKEN }}
